### ISSUE TITLE
Affichage des commentaires 

### ISSUE THREAD

**Issue by etienne582** [flashino/flashino#15]
<a href='http://i.imgur.com/UYVwRkQ' title=''><img src='http://i.imgur.com/UYVwRkQ.jpg' alt='' title='Hosted by imgur.com' /></a>

**Comment by marco219** [comment]
Ce bug a été corrigé lors de la dernière mise à jour.
Merci de tenir votre application à jour

**Comment by etienne582** [comment]
Pouvez vous l'indiquer comment obtenir cette fameuse mise à jours svp

**Comment by marco219** [comment]
Il suffit pour cela de vous rendre dans les locaux de développement
flashino au 105 rue du général de Gaulle, Enghien les bains, France.
