### ISSUE TITLE
Crypter les mots de passe

### ISSUE THREAD

**Issue by etienne582** [flashino/flashino#22]

**Comment by marco219** [comment]
il faut arrêter des cryptage bidon type md5, sha mais plutôt utiliser un cryptage par clés("salt").
http://www.apprendre-php.com/tutoriels/tutoriel-35-scuriser-les-mots-de-passe-avec-les-hashs-et-les-salts.html

**Comment by etienne582** [comment]
Je pense le md5 c'est obsolète après ouai peux être un mix sha256 ou 512
